#!/usr/bin/env python3
import argparse
import json
from requests import get

parser = argparse.ArgumentParser(description = "Мониторинг Astra - Обнаружение")
parser.add_argument('type', help = 'type of discovery(channels|dvbs')
args = parser.parse_args()

try:
  if args.type == 'channels':
    #print('Discovering channels')
    r = get("http://IP.Collector:8080/cfg_channels/", timeout = 15)
    js0n = r.json()
    data = {}
    chs = []
    for i in js0n:
      ch = {}
      ch['{#CH_ID}'] = i
      ch['{#CH_NAME}'] = js0n[i]['channel']['name']
      chs.append(ch)
    data['data'] = chs
    print(json.dumps(data, ensure_ascii=False))

  if args.type == 'dvbs':
    #print('Discovering dvbs')
    r = get("http://IP.Collector:8080/cfg_dvbs/", timeout = 15)
    js0n = r.json()
    data = {}
    dvbs = []
    for i in js0n:
      dvb = {}
      dvb['{#DVB_ID}'] = i
      dvb['{#DVB_NAME}'] = js0n[i]['dvb']['name']
      dvbs.append(dvb)
    data['data'] = dvbs
    print(json.dumps(data, ensure_ascii=False))
except:
  print("nodata")


