{
 "title": "Channels",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Name",
    "label": "Name",
    "query": "SHOW TAG VALUES FROM \"stream\" WITH KEY = \"id\""
   },
   {
    "name": "Address",
    "label": "Address",
    "query": "SHOW TAG VALUES FROM \"stream\" WITH KEY = \"addr\" WHERE \"name\" = '$Name'"
   },
   {
    "name": "Current",
    "label": "Current",
    "query": "SHOW TAG VALUES FROM \"stream\" WITH KEY = \"id\""
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Current -- $Address",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "Bitrate",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stream",
     "query": "SELECT mean(\"bitrate\") FROM \"stream\" WHERE \"id\" =~ /^$Name$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Current$/" }
     ]
    },
    {
     "alias": "CC Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stream",
     "query": "SELECT mean(\"cc\")  *800 FROM \"stream\" WHERE \"id\" =~ /^$Name$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "cc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$Name$/" }
     ]
    }
   ]
  },
  {
   "title": "Total CC Error",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stream",
     "query": "SELECT mean(\"cc\") *80 FROM \"stream\" WHERE \"id\" <> 'select tag value' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cc" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "<>", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Total Bitrate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "stream",
     "query": "SELECT mean(\"bitrate\")  FROM \"stream\" WHERE \"id\" <> 'select tag value' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "<>", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Channel",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "stream",
     "select": [
      [
       { "params": [ "addr" ], "type": "field" }
      ],
      [
       { "params": [ "bitrate" ], "type": "field" }
      ],
      [
       { "params": [ "cc" ], "type": "field" }
      ],
      [
       { "params": [ "onair" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "<>", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "content": "<script src=\"https://cdn.jsdelivr.net/npm/hls.js@latest\"></script>\r\n<video id=\"video\"width=\"640\" height=\"350\" ></video>\r\n<script>\r\n  if(Hls.isSupported()) {\r\n    var video = document.getElementById('video');\r\n    var hls = new Hls();\r\n    hls.loadSource('http://ТВОЙ IP:9998/play/$Current/index.m3u8');\r\n    hls.attachMedia(video);\r\n    hls.on(Hls.Events.MANIFEST_PARSED,function() {\r\n      video.play();\r\n  });\r\n }\r\n // hls.js is not supported on platforms that do not have Media Source Extensions (MSE) enabled.\r\n // When the browser has built-in HLS support (check using `canPlayType`), we can provide an HLS manifest (i.e. .m3u8 URL) directly to the video element throught the `src` property.\r\n // This is using the built-in support of the plain video element, without using hls.js.\r\n  else if (video.canPlayType('application/vnd.apple.mpegurl')) {\r\n    video.src = 'http://ТВОЙ IP:9998/play/$Current/index.m3u8';\r\n    video.addEventListener('canplay',function() {\r\n      video.play();\r\n    });\r\n  }\r\n</script>\r\n"
  },
  {
   "title": "$Name",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "repeat": "Name",
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stream",
     "query": "SELECT mean(\"bitrate\"), mean(\"cc\") FROM \"stream\" WHERE \"id\" = '$Name' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "cc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*800" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=", "value": "Первый" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}